---
- name: Check ROS packages profile state
  ansible.builtin.import_tasks: profile_guard.yaml

- name: Configure current ROS 2 APT repository
  ansible.builtin.import_tasks: repository_current.yaml
  when: ros2_snapshot_date | length == 0

- name: Configure ROS 2 snapshot APT repository
  ansible.builtin.import_tasks: repository_snapshot.yaml
  when: ros2_snapshot_date | length > 0

- name: Install ros-{{ ros_distro }}-{{ ros2_installation_type }}
  become: true
  ansible.builtin.apt:
    name: ros-{{ ros_distro }}-{{ ros2_installation_type }}
    state: present
    allow_downgrade: "{{ use_locked_versions | default(false) | bool }}"
  tags:
    - ros2
    - core

- name: Add ROS 2 setup.bash to user's .bashrc
  ansible.builtin.lineinfile:
    dest: "{{ ansible_env.HOME }}/.bashrc"
    line: source /opt/ros/{{ ros_distro }}/setup.bash
    state: present
    create: true
    mode: 0644
  tags:
    - ros2
    - core
