---
- name: Install MAVROS packages
  become: true
  ansible.builtin.apt:
    name:
      - "ros-{{ ros_distro }}-mavros"
      - "ros-{{ ros_distro }}-mavros-extras"
      - "ros-{{ ros_distro }}-mavros-msgs"
    state: present
  tags:
    - mavros
    - core
    - simulation
