PACKAGE_NAME="g2o"

PACKAGE_REPO_TYPE="git"
PACKAGE_REPO_URL="https://github.com/RainerKuemmerle/g2o.git"
PACKAGE_REPO_BRANCH="master"

PACKAGE_BUILDDEPS="build-essential cmake debhelper libeigen3-dev libsuitesparse-dev libspdlog-dev"