- name: Install MAVROS
  hosts: "{{ target | default('local') }}"
  vars_files:
    - vars/ros_packages_profiles.yaml

  pre_tasks:
    - name: Resolve ROS packages profile
      ansible.builtin.import_tasks: tasks/resolve_ros_packages_profile.yaml
      tags: always

  roles:
    - role: clover2.dev.ros2
      tags: [ros2, mavros]

    - role: clover2.dev.mavros
      tags: [mavros]
