BOARD=uefi-arm64
BRANCH=current
RELEASE=noble
KERNEL_CONFIGURE=no
BUILD_DESKTOP=yes
DESKTOP_ENVIRONMENT="xfce"
DESKTOP_TIER="minimal"
BUILD_MINIMAL=no
SHARE_LOGS=no

BOARD_NAME="Clover2 Virtual Box"
BOARD_MAINTAINER="matveylapin"
BOARDFAMILY="uefi-arm64"

VENDOR="Clover2"
MAINTAINER="matveylapin"

FIRST_BOOT_LOAD_CMDLEVEL=1
