---
- name: Install geographiclib packages
  become: true
  ansible.builtin.apt:
    name:
      - geographiclib-tools
      - libgeographiclib-dev
    state: latest
    update_cache: true

- name: Install GeographicLib datasets
  become: true
  ansible.builtin.command:
    cmd: "geographiclib-get-{{ item.tool }} {{ item.model }}"
    creates: /usr/share/GeographicLib/{{ item.tool }}/{{ item.model }}.pgm
  loop:
    - { tool: geoids, model: egm96-5 }
    - { tool: gravity, model: egm96 }
    - { tool: magnetic, model: emm2015 }
