---
- name: Remove old
  become: true
  ansible.builtin.apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
    state: absent
    update_cache: true
  tags:
    - docker

- name: Install dependencies
  become: true
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: true
  tags:
    - docker

- name: Create the directory for keyrings
  become: true
  ansible.builtin.file:
    state: directory
    path: /etc/apt/keyrings
    mode: "0755"
  tags:
    - docker

- name: Download Docker GPG key
  become: true
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: "0644"
  tags:
    - docker

- name: Save result of 'dpkg --print-architecture'
  ansible.builtin.command: dpkg --print-architecture
  register: docker_engine__deb_architecture
  changed_when: false
  tags:
    - docker

- name: Add Docker apt repository to source list
  become: true
  ansible.builtin.apt_repository:
    repo: deb [arch={{ docker_engine__deb_architecture.stdout }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/{{ ansible_facts['lsb']['id'] | lower }} {{ ansible_facts['lsb']['codename'] }} stable
    filename: docker
    state: present
    update_cache: true
  tags:
    - docker

- name: Install Docker Engine
  become: true
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-v2
    state: present
    allow_downgrade: "{{ use_locked_versions | default(false) | bool }}"
    update_cache: true
  tags:
    - docker

- name: Add docker group
  become: true
  ansible.builtin.group:
    name: docker
    state: present
  tags:
    - docker

- name: Add user to docker group
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: true
  tags:
    - docker
