name: Cleanup Container Registry

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'List what would be deleted'
        type: boolean
        default: false

permissions:
  packages: write

jobs:
  clean-ghcr:
    runs-on: ubuntu-latest
    steps:
      - uses: snok/container-retention-policy@v3.1.0
        with:
          account: klever-coex
          token: ${{ secrets.GH_PAT }}
          image-names: "clover2-dev/*"
          cut-off: 7d
          keep-n-most-recent: 10
          image-tags: "!latest !stable !v* !pre-release"
          dry-run: ${{ inputs.dry_run == true }}
          tag-selection: both
