name: docker-build-template

on:
  workflow_call:
    inputs:
      needs-source:
        description: Clone repos to build
        type: boolean
        default: false


jobs:
  build:
    name: ${{ inputs.bake-group }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      actions: write
    steps:
      - name: Import VCS source repos
        if: inputs.needs-source
        run: |
          pipx install vcs2l
          mkdir -p src
          vcs import --shallow src < repositories/autoware.repos

      - name: Build and push
        uses: docker/bake-action@v7
        with:
          source: .
          files: docker/docker-bake.hcl
          targets: default
          push: true
          set: |
            *.cache-from=type=gha,scope=clover2-dev
            *.cache-to=type=gha,scope=clover2-dev,mode=max
          vars: |
            BUILD_MODE=${{ needs.detect-mode.outputs.build_mode }}
            CLOVER2_DEV_GIT_HASH=${{ needs.detect-mode.outputs.git_hash }}
            CLOVER2_DEV_VERSION=${{ needs.detect-mode.outputs.version }}
            USE_REGISTRY_CONTEXTS=false